// AUTO-GENERATED by scripts/build.ts. Stub for dev mode.
// `bun run build` overwrites this file with embedded-asset imports,
// then restores the stub on completion.
export const assets = new Map<string, string>();
export const indexHtml: string | undefined = undefined;
