import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { Glob } from 'bun';

const { values } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    target: { type: 'string' },
    outfile: { type: 'string' },
  },
  strict: true,
  allowPositionals: false,
});

const TARGET = values.target ?? 'bun';
const OUTFILE = values.outfile ?? 'jottapp';

const ROOT = process.cwd();
const DIST = resolve(ROOT, 'dist');
const MANIFEST = resolve(ROOT, 'backend/staticAssets.generated.ts');
const BINARY_NAME = TARGET.includes('windows') ? `${OUTFILE}.exe` : OUTFILE;
const BINARY = resolve(ROOT, BINARY_NAME);

const STUB = `// AUTO-GENERATED by scripts/build.ts. Stub for dev mode.
// \`bun run build\` overwrites this file with embedded-asset imports,
// then restores the stub on completion.
export const assets = new Map<string, string>();
export const indexHtml: string | undefined = undefined;
`;

async function run(cmd: string[]): Promise<void> {
  const p = Bun.spawn(cmd, { stdio: ['inherit', 'inherit', 'inherit'] });
  const code = await p.exited;
  if (code !== 0) throw new Error(`${cmd.join(' ')} exited with code ${code}`);
}

async function listDist(): Promise<string[]> {
  const glob = new Glob('**/*');
  const files: string[] = [];
  for await (const f of glob.scan({ cwd: DIST, onlyFiles: true })) {
    files.push(f);
  }
  files.sort();
  return files;
}

function renderManifest(files: string[]): string {
  const lines: string[] = ['// @ts-nocheck', '// AUTO-GENERATED by scripts/build.ts', ''];
  const entries: string[] = [];
  files.forEach((file, i) => {
    const id = `a${i}`;
    lines.push(`import ${id} from '../dist/${file}' with { type: 'file' };`);
    entries.push(`  ['/${file}', ${id}],`);
  });
  lines.push('');
  lines.push('export const assets = new Map<string, string>([');
  lines.push(...entries);
  lines.push(']);');
  lines.push('');
  lines.push("export const indexHtml: string | undefined = assets.get('/index.html');");
  lines.push('');
  return lines.join('\n');
}

async function build(): Promise<void> {
  process.stdout.write('▸ vite build…\n');
  await run(['bun', '--bun', 'vite', 'build']);

  const files = await listDist();
  if (files.length === 0) throw new Error('dist/ is empty after vite build');
  process.stdout.write(`▸ embedding ${files.length} asset${files.length === 1 ? '' : 's'}…\n`);

  await writeFile(MANIFEST, renderManifest(files));

  process.stdout.write(`▸ bun build --compile --target=${TARGET}…\n`);
  await run([
    'bun',
    'build',
    '--compile',
    `--target=${TARGET}`,
    '--minify',
    'backend/index.ts',
    `--outfile=${OUTFILE}`,
  ]);

  const sizeMb = Bun.file(BINARY).size / 1_000_000;
  process.stdout.write(`✓ built ${BINARY} (${sizeMb.toFixed(1)} MB)\n`);
}

try {
  await build();
} finally {
  await writeFile(MANIFEST, STUB);
}
